services:
  postgres:
    image: postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "sagenda-rw"
      POSTGRES_PASSWORD: "sagenda-rw-secret"
      POSTGRES_DB: "sagenda"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sagenda-rw -d sagenda"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "sagenda-rw"
      DB_PASSWORD: "sagenda-rw-secret"
      DB_DATABASE: "sagenda"
    ports:
      - "3000:3000"
