services:
  postgres:
    image: postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "sagenda"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "!Letm3in!"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d sagenda"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
